# Defines the application's Docker image and additional services
# https://docs.docker.com/compose/compose-file/
# To run using docker-compose, use the command:
#   docker-compose up --build todo

version: '3'
services:
  todo:
    build:
      context: .
      dockerfile: dev.Dockerfile

    working_dir: /app

    # Ports to expose to the host. Uncomment if running outside of vscode.
    # ports:
      # - 5001:5001

    # Volumes to mount from the host.
    volumes:
      # Mount local source folder into container
      - .:/app
      # Add volume for vscode extensions
      - todo-vscode-extensions:/home/vscode/.vscode-server/extensions
      # mountpoints for kubernetes syncing.
      - ${HOME}/.kube:/usr/local/share/kube-localhost:cached
      - ${HOME}/.minikube:/usr/local/share/minikube-localhost:cached

    environment:
      #FLASK_APP: todo:app
      FLASK_DEBUG: 1
      #FLASK_RUN_PORT: 5001

    ## Don't restart container if it exits. Useful for debugging, not for production.
    restart: 'no'
    depends_on:
      - mongodb
    
  todo-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    working_dir: /frontend
    volumes:
      - ./src/frontend/src:/frontend/src
      - /frontend/node_modules
      - todo-front-extensions:/home/vscode/.vscode-server/extensions
    # environment:
    ports:
      - 5173:5173

  mongodb:
    image: mongo:4.2
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  todo-vscode-extensions:

  todo-front-extensions:

  mongodb-data: